apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'fairdevops-api'
        static_configs:
          - targets: ['fairdevops-api:8080']
        metrics_path: '/metrics'
        scrape_interval: 10s 